#!/usr/bin/env python3
"""Parse careerfairchecklist/*.csv and emit SQL to replace questions per program type."""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

# Filename stem -> program_types.name (edit if your Supabase names differ)
PROGRAM_TYPE_BY_FILE = {
    "college": "College",
    "military": "Military",
    "job": "Job",
    "apprenticeship": "Apprenticeship",
}


def map_response_type(raw: str) -> str:
    if not raw or not raw.strip():
        return "text"
    s = raw.strip().lower()
    if s in ("numerical", "number"):
        return "number"
    if s == "date":
        return "date"
    if "money" in s:
        return "money"
    if s in ("boolean", "yes / no", "yes/no"):
        return "boolean"
    # short answer, drop down, options:, type of response, etc.
    return "text"


def looks_like_section_header(col0: str, col1: str) -> bool:
    """Row is a section title when col2 is empty and col1 is ALL CAPS (spreadsheet blocks)."""
    if not col0 or not col0.strip():
        return False
    if col1 and col1.strip():
        return False
    c0 = col0.strip().rstrip(",")
    if "?" in c0:
        return False
    if len(c0) > 180:
        return False
    letters = "".join(ch for ch in c0 if ch.isalpha())
    if not letters:
        return False
    return c0.upper() == c0


def read_rows(path: Path) -> list[list[str]]:
    text = path.read_text(encoding="utf-8-sig", errors="replace")
    # Normalize newlines
    lines = text.splitlines()
    rows: list[list[str]] = []
    for line in lines:
        if not line.strip():
            continue
        rows.append(next(csv.reader([line])))
    return rows


def parse_file(path: Path) -> tuple[list[tuple[str | None, str, str]], str]:
    """
    Returns (list of (section_title_or_none, label, type)),
    program_type_name
    """
    stem = path.stem.lower()
    ptype = PROGRAM_TYPE_BY_FILE.get(stem)
    if not ptype:
        raise ValueError(f"Unknown file {path.name}, add to PROGRAM_TYPE_BY_FILE")

    rows = read_rows(path)
    if not rows:
        return [], ptype

    out: list[tuple[str | None, str, str]] = []
    section: str | None = None
    start_idx = 0

    # Skip first row (sheet title)
    if rows:
        start_idx = 1

    # Optional second row: first section name + "Type of response" header
    if len(rows) > start_idx:
        r = rows[start_idx]
        c0 = r[0].strip() if r else ""
        c1 = r[1].strip() if len(r) > 1 else ""
        if "type" in c1.lower() and "response" in c1.lower():
            section = c0.rstrip(",").strip() or None
            start_idx += 1

    i = start_idx
    while i < len(rows):
        r = rows[i]
        c0 = r[0].strip() if len(r) > 0 else ""
        c1 = r[1].strip() if len(r) > 1 else ""

        if not c0:
            i += 1
            continue

        if looks_like_section_header(c0, c1):
            section = c0.rstrip(",").strip()
            i += 1
            continue

        label = c0
        rtype = map_response_type(c1)
        out.append((section, label, rtype))
        i += 1

    return out, ptype


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def emit_sql(files: list[Path]) -> str:
    lines: list[str] = [
        "-- Generated by supabase/generate_questions_sql.py",
        "-- Overwrites questions (and related sections) for each program type named below.",
        "-- Verify names: SELECT id, name FROM public.program_types ORDER BY name;",
        "",
        "BEGIN;",
        "",
    ]

    for path in files:
        items, ptype = parse_file(path)
        lines.append(f"-- ---- {path.name} -> program_types.name = '{sql_escape(ptype)}' ----")
        lines.append(
            f"DELETE FROM public.questions WHERE program_type_id = "
            f"(SELECT id FROM public.program_types WHERE name = '{sql_escape(ptype)}');"
        )
        lines.append(
            f"DELETE FROM public.question_sections WHERE program_type_id = "
            f"(SELECT id FROM public.program_types WHERE name = '{sql_escape(ptype)}');"
        )
        lines.append("")

        # Collect unique sections in order
        seen: list[str] = []
        for sec, _, _ in items:
            if sec and sec not in seen:
                seen.append(sec)

        section_id_expr: dict[str, str] = {}
        for s in seen:
            var = re.sub(r"[^a-zA-Z0-9_]", "_", s)[:40]
            lines.append(
                f"INSERT INTO public.question_sections (id, program_type_id, title, sort_order)\n"
                f"SELECT gen_random_uuid(), id, '{sql_escape(s)}', {seen.index(s)}\n"
                f"FROM public.program_types WHERE name = '{sql_escape(ptype)}';"
            )
            section_id_expr[s] = (
                f"(SELECT id FROM public.question_sections qs WHERE qs.program_type_id = "
                f"(SELECT id FROM public.program_types WHERE name = '{sql_escape(ptype)}') "
                f"AND qs.title = '{sql_escape(s)}' LIMIT 1)"
            )

        lines.append("")
        sort_order = 0
        for sec, label, rtype in items:
            sort_order += 1
            sec_sql = "NULL"
            if sec:
                sec_sql = section_id_expr[sec]
            lines.append(
                "INSERT INTO public.questions (id, program_type_id, label, sort_order, type, section_id)\n"
                "SELECT gen_random_uuid(), id, "
                f"'{sql_escape(label)}', {sort_order}, '{rtype}', {sec_sql}\n"
                f"FROM public.program_types WHERE name = '{sql_escape(ptype)}';"
            )
        lines.append("")

    lines.append("COMMIT;")
    return "\n".join(lines)


def main() -> None:
    base = Path(__file__).resolve().parent.parent.parent  # careerfairchecklist
    names = ["college.csv", "military.csv", "job.csv", "apprenticeship.csv"]
    files = [base / n for n in names]
    for f in files:
        if not f.is_file():
            print(f"Missing {f}", file=sys.stderr)
            sys.exit(1)
    sql = emit_sql(files)
    out = Path(__file__).resolve().parent / "questions_from_csv.sql"
    out.write_text(sql, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
